/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   hero_msg__init
                     (HeroMsg         *message)
{
  static HeroMsg init_value = HERO_MSG__INIT;
  *message = init_value;
}
size_t hero_msg__get_packed_size
                     (const HeroMsg *message)
{
  assert(message->base.descriptor == &hero_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hero_msg__pack
                     (const HeroMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hero_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hero_msg__pack_to_buffer
                     (const HeroMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hero_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HeroMsg *
       hero_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HeroMsg *)
     protobuf_c_message_unpack (&hero_msg__descriptor,
                                allocator, len, data);
}
void   hero_msg__free_unpacked
                     (HeroMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &hero_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_req__init
                     (LoginReq         *message)
{
  static LoginReq init_value = LOGIN_REQ__INIT;
  *message = init_value;
}
size_t login_req__get_packed_size
                     (const LoginReq *message)
{
  assert(message->base.descriptor == &login_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_req__pack
                     (const LoginReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_req__pack_to_buffer
                     (const LoginReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginReq *
       login_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginReq *)
     protobuf_c_message_unpack (&login_req__descriptor,
                                allocator, len, data);
}
void   login_req__free_unpacked
                     (LoginReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &login_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_rsp__init
                     (LoginRsp         *message)
{
  static LoginRsp init_value = LOGIN_RSP__INIT;
  *message = init_value;
}
size_t login_rsp__get_packed_size
                     (const LoginRsp *message)
{
  assert(message->base.descriptor == &login_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_rsp__pack
                     (const LoginRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_rsp__pack_to_buffer
                     (const LoginRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginRsp *
       login_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginRsp *)
     protobuf_c_message_unpack (&login_rsp__descriptor,
                                allocator, len, data);
}
void   login_rsp__free_unpacked
                     (LoginRsp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &login_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   enemy_msg__init
                     (EnemyMsg         *message)
{
  static EnemyMsg init_value = ENEMY_MSG__INIT;
  *message = init_value;
}
size_t enemy_msg__get_packed_size
                     (const EnemyMsg *message)
{
  assert(message->base.descriptor == &enemy_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t enemy_msg__pack
                     (const EnemyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &enemy_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t enemy_msg__pack_to_buffer
                     (const EnemyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &enemy_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EnemyMsg *
       enemy_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EnemyMsg *)
     protobuf_c_message_unpack (&enemy_msg__descriptor,
                                allocator, len, data);
}
void   enemy_msg__free_unpacked
                     (EnemyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &enemy_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   new_enemy__init
                     (NewEnemy         *message)
{
  static NewEnemy init_value = NEW_ENEMY__INIT;
  *message = init_value;
}
size_t new_enemy__get_packed_size
                     (const NewEnemy *message)
{
  assert(message->base.descriptor == &new_enemy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t new_enemy__pack
                     (const NewEnemy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &new_enemy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t new_enemy__pack_to_buffer
                     (const NewEnemy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &new_enemy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NewEnemy *
       new_enemy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NewEnemy *)
     protobuf_c_message_unpack (&new_enemy__descriptor,
                                allocator, len, data);
}
void   new_enemy__free_unpacked
                     (NewEnemy *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &new_enemy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_req__init
                     (StartReq         *message)
{
  static StartReq init_value = START_REQ__INIT;
  *message = init_value;
}
size_t start_req__get_packed_size
                     (const StartReq *message)
{
  assert(message->base.descriptor == &start_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_req__pack
                     (const StartReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_req__pack_to_buffer
                     (const StartReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartReq *
       start_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartReq *)
     protobuf_c_message_unpack (&start_req__descriptor,
                                allocator, len, data);
}
void   start_req__free_unpacked
                     (StartReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &start_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_rsp__init
                     (StartRsp         *message)
{
  static StartRsp init_value = START_RSP__INIT;
  *message = init_value;
}
size_t start_rsp__get_packed_size
                     (const StartRsp *message)
{
  assert(message->base.descriptor == &start_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_rsp__pack
                     (const StartRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_rsp__pack_to_buffer
                     (const StartRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartRsp *
       start_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartRsp *)
     protobuf_c_message_unpack (&start_rsp__descriptor,
                                allocator, len, data);
}
void   start_rsp__free_unpacked
                     (StartRsp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &start_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_end__init
                     (LoginEnd         *message)
{
  static LoginEnd init_value = LOGIN_END__INIT;
  *message = init_value;
}
size_t login_end__get_packed_size
                     (const LoginEnd *message)
{
  assert(message->base.descriptor == &login_end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_end__pack
                     (const LoginEnd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_end__pack_to_buffer
                     (const LoginEnd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginEnd *
       login_end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginEnd *)
     protobuf_c_message_unpack (&login_end__descriptor,
                                allocator, len, data);
}
void   login_end__free_unpacked
                     (LoginEnd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &login_end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hero_msg__field_descriptors[3] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HeroMsg, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HeroMsg, point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HeroMsg, point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hero_msg__field_indices_by_name[] = {
  1,   /* field[1] = point_x */
  2,   /* field[2] = point_y */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange hero_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hero_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hero_msg",
  "HeroMsg",
  "HeroMsg",
  "",
  sizeof(HeroMsg),
  3,
  hero_msg__field_descriptors,
  hero_msg__field_indices_by_name,
  1,  hero_msg__number_ranges,
  (ProtobufCMessageInit) hero_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange login_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor login_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "login_req",
  "LoginReq",
  "LoginReq",
  "",
  sizeof(LoginReq),
  1,
  login_req__field_descriptors,
  login_req__field_indices_by_name,
  1,  login_req__number_ranges,
  (ProtobufCMessageInit) login_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_rsp__field_descriptors[4] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoginRsp, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LoginRsp, point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LoginRsp, point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enemy_num",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LoginRsp, enemy_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_rsp__field_indices_by_name[] = {
  3,   /* field[3] = enemy_num */
  1,   /* field[1] = point_x */
  2,   /* field[2] = point_y */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange login_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor login_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "login_rsp",
  "LoginRsp",
  "LoginRsp",
  "",
  sizeof(LoginRsp),
  4,
  login_rsp__field_descriptors,
  login_rsp__field_indices_by_name,
  1,  login_rsp__number_ranges,
  (ProtobufCMessageInit) login_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor enemy_msg__field_descriptors[3] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EnemyMsg, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EnemyMsg, point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EnemyMsg, point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned enemy_msg__field_indices_by_name[] = {
  1,   /* field[1] = point_x */
  2,   /* field[2] = point_y */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange enemy_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor enemy_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "enemy_msg",
  "EnemyMsg",
  "EnemyMsg",
  "",
  sizeof(EnemyMsg),
  3,
  enemy_msg__field_descriptors,
  enemy_msg__field_indices_by_name,
  1,  enemy_msg__number_ranges,
  (ProtobufCMessageInit) enemy_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor new_enemy__field_descriptors[3] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewEnemy, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewEnemy, point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewEnemy, point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned new_enemy__field_indices_by_name[] = {
  1,   /* field[1] = point_x */
  2,   /* field[2] = point_y */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange new_enemy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor new_enemy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "new_enemy",
  "NewEnemy",
  "NewEnemy",
  "",
  sizeof(NewEnemy),
  3,
  new_enemy__field_descriptors,
  new_enemy__field_indices_by_name,
  1,  new_enemy__number_ranges,
  (ProtobufCMessageInit) new_enemy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_req__field_descriptors[1] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(StartReq, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_req__field_indices_by_name[] = {
  0,   /* field[0] = start */
};
static const ProtobufCIntRange start_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor start_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "start_req",
  "StartReq",
  "StartReq",
  "",
  sizeof(StartReq),
  1,
  start_req__field_descriptors,
  start_req__field_indices_by_name,
  1,  start_req__number_ranges,
  (ProtobufCMessageInit) start_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_rsp__field_descriptors[1] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(StartRsp, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_rsp__field_indices_by_name[] = {
  0,   /* field[0] = start */
};
static const ProtobufCIntRange start_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor start_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "start_rsp",
  "StartRsp",
  "StartRsp",
  "",
  sizeof(StartRsp),
  1,
  start_rsp__field_descriptors,
  start_rsp__field_indices_by_name,
  1,  start_rsp__number_ranges,
  (ProtobufCMessageInit) start_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_end__field_descriptors[1] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoginEnd, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_end__field_indices_by_name[] = {
  0,   /* field[0] = success */
};
static const ProtobufCIntRange login_end__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor login_end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "login_end",
  "LoginEnd",
  "LoginEnd",
  "",
  sizeof(LoginEnd),
  1,
  login_end__field_descriptors,
  login_end__field_indices_by_name,
  1,  login_end__number_ranges,
  (ProtobufCMessageInit) login_end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
