#ifndef _SERVICE_PORT_H
#define _SERVICE_PORT_H

#define PORT_NETWORK_IO_SERVICE    				8000
#define PORT_NETLOGIC_SERVICE      				8009

#define PORT_GAME_LOGIC_SERVICE_FIRST   	8002
#define PORT_GAME_LOGIC_SERVICE_SECOND  	8003
#define PORT_GAME_LOGIC_SERVICE_THIRD   	8004
#define PORT_GAME_LOGIC_SERVICE_FOURTH  	8005

#endif
