#ifndef _SERVICE_PORT_H
#define _SERVICE_PORT_H

#define PORT_NETWORK_IO_SERVICE    				8000
#define PORT_NETROUTE_SERVICE_LISTENING			8001
#define PORT_NETROUTE_2_NETIO_SERVICE        	8002

#define PORT_GAME_LOGIC_SERVICE_FIRST   		8003
#define PORT_GAME_LOGIC_SERVICE_SECOND  		8004
#define PORT_GAME_LOGIC_SERVICE_THIRD   		8005
#define PORT_GAME_LOGIC_SERVICE_FOURTH  		8006


#endif
