#ifndef _SERVICE_PORT_H
#define _SERVICE_PORT_H

#define NETWORK_IO_SERVICE_PORT    8000
#define NETLOGIC_SERVICE_PORT      8001

#define GAME_LOGIC_SERVICE_FIRST   8002
#define GAME_LOGIC_SERVICE_SECOND  8003
#define GAME_LOGIC_SERVICE_THIRD   8004
#define GAME_LOGIC_SERVICE_FOURTH  8005

#endif
